services:
    rabbitmq:
        image: rabbitmq:3.9.22
        container_name: rabbitssl
        ports:
            - 5671:5671
            - 5672:5672
        volumes:
            - "./ssl/ca_certificate.pem:/etc/ssl/rabbit/ca_certificate.pem"
            - "./ssl/server_certificate.pem:/etc/ssl/rabbit/server_certificate.pem"
            - "./ssl/server_key.pem:/etc/ssl/rabbit/server_key.pem"
            - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
